import localFont from "next/font/local";

import AuthProvider from "@/context/AuthProvider";
import Footer from "@/ui/components/footer/footer";
import Header from "@/ui/components/header/header";
import ThemeProvider from "@/ui/components/theme-provider/themeProvider";

import styles from "./layout.module.scss";

import type { Metadata } from "next";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${styles.layout__body}`}
            >
                <AuthProvider>
                    <ThemeProvider>
                        <Header />
                        <main className={styles.layout__main}>{children}</main>
                        <Footer />
                    </ThemeProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
